site_name: Detect-Teppe doc
site_description: Centralized documentation for onboarding on detect-teppe project
site_author: Laura Dumont
site_url: https://www.aura.healthcare

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      accent: lime

nav:
  - Home: index.md
  - Aura Project Overview: project-overview.md
  - Getting Started:
    - Quick Start Guide: getting-started/quick-start.md
  - User Guide:
    - Basic Usage: user-guide/basic-usage.md
  - Developer Guide:
    - Architecture Overview: dev-guide/architecture.md
    - Contributing: dev-guide/contributing.md
  - FAQ: faq.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/Aura-healthcare"  target="_blank" rel="noopener">Laura Dumont</a>

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Aura-healthcare
    - icon: fontawesome/brands/discord
      link: https://discord.com
    - icon: fontawesome/brands/chrome
      link: https://en.aura.healthcare/
    - icon: fontawesome/solid/envelope
      link: mailto:contact@aura.healthcare