name: Deploy MkDocs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install the latest version of uv
        uses: eifinger/setup-uv@v2
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          uv sync
      - name: Build and deploy
        run: |
          uv run mkdocs gh-deploy --force